In [1]:
import pandas as pd

#load dataset
df = pd.read_csv(r"C:\Users\byobd\OneDrive\Desktop\Data-Analysis-And-Automation\Sample Data\data_jobs.csv")
df.head()

# cleaning the dataset
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [2]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [3]:
df_kenya = df[df['job_country'] == 'Kenya'].copy()

In [4]:
df_kenya

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1059,Cloud Engineer,Navigation & Infrastructure Engineer,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-08-06 13:50:21,False,False,Kenya,NaN,NaN,NaN,Kenya Airways,NaN,NaN
1705,Data Analyst,"Data Analytics Program Manager, VisionFund Int...","Nairobi, Kenya",via MyJobMag,Full-time,False,Kenya,2023-02-09 13:40:24,False,False,Kenya,NaN,NaN,NaN,World Vision Kenya,['tableau'],{'analyst_tools': ['tableau']}
2089,Data Scientist,Data Scientist,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-05-25 13:39:11,False,False,Kenya,NaN,NaN,NaN,Medtronic Labs,"['go', 'python', 'aws', 'docker']","{'cloud': ['aws'], 'other': ['docker'], 'progr..."
2279,Data Scientist,Director of Data,Kenya,via Trabajo.org,Full-time,False,Kenya,2023-05-25 13:39:14,True,False,Kenya,NaN,NaN,NaN,KOKO NETWORKS,NaN,NaN
3482,Data Analyst,Data Analyst,"Nairobi, Kenya",via UNjobnet,Full-time,False,Kenya,2023-03-22 13:47:56,False,False,Kenya,NaN,NaN,NaN,United Nations Human Settlements Programme,['c'],{'programming': ['c']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783724,Data Scientist,Data Science Intern at Dataposit,"Nairobi, Kenya",via BeBee Kenya,Full-time and Internship,False,Kenya,2023-09-18 06:19:21,False,False,Kenya,NaN,NaN,NaN,Dataposit,"['r', 'python', 'matlab', 'java', 'c']","{'programming': ['r', 'python', 'matlab', 'jav..."
784558,Cloud Engineer,Data Insights Analytics Cloud Support Engineer,"Nairobi, Kenya",via BrighterMonday,Full-time,False,Kenya,2023-11-16 06:31:16,False,False,Kenya,NaN,NaN,NaN,confidential,"['python', 'r', 'ruby', 'ruby', 'go', 'java', ...","{'cloud': ['aws', 'redshift', 'oracle'], 'data..."
784798,Senior Data Scientist,Senior Analyst,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,2023-10-29 06:22:25,False,False,Kenya,NaN,NaN,NaN,Habitat for Humanity International,"['sas', 'sas', 'r', 'tableau']","{'analyst_tools': ['sas', 'tableau'], 'program..."
784991,Cloud Engineer,Senior Engineering Technician,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-08-12 06:19:49,True,False,Kenya,NaN,NaN,NaN,Kenya Marine and Fisheries Research Institute ...,['c'],{'programming': ['c']}
785115,Data Analyst,Data Analyst.,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-05-31 06:25:53,False,False,Kenya,NaN,NaN,NaN,Supreme,"['sql', 'python', 'r', 'excel', 'tableau', 'po...","{'analyst_tools': ['excel', 'tableau', 'power ..."

In [5]:
# Extract month and year from job_posted_date in verbage format

df_kenya['job_posted_month'] = df_kenya['job_posted_date'].dt.strftime('%B') #refer from datetime documentation for % sighns

In [6]:
df_kenya

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
1059,Cloud Engineer,Navigation & Infrastructure Engineer,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-08-06 13:50:21,False,False,Kenya,NaN,NaN,NaN,Kenya Airways,NaN,NaN,August
1705,Data Analyst,"Data Analytics Program Manager, VisionFund Int...","Nairobi, Kenya",via MyJobMag,Full-time,False,Kenya,2023-02-09 13:40:24,False,False,Kenya,NaN,NaN,NaN,World Vision Kenya,['tableau'],{'analyst_tools': ['tableau']},February
2089,Data Scientist,Data Scientist,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-05-25 13:39:11,False,False,Kenya,NaN,NaN,NaN,Medtronic Labs,"['go', 'python', 'aws', 'docker']","{'cloud': ['aws'], 'other': ['docker'], 'progr...",May
2279,Data Scientist,Director of Data,Kenya,via Trabajo.org,Full-time,False,Kenya,2023-05-25 13:39:14,True,False,Kenya,NaN,NaN,NaN,KOKO NETWORKS,NaN,NaN,May
3482,Data Analyst,Data Analyst,"Nairobi, Kenya",via UNjobnet,Full-time,False,Kenya,2023-03-22 13:47:56,False,False,Kenya,NaN,NaN,NaN,United Nations Human Settlements Programme,['c'],{'programming': ['c']},March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783724,Data Scientist,Data Science Intern at Dataposit,"Nairobi, Kenya",via BeBee Kenya,Full-time and Internship,False,Kenya,2023-09-18 06:19:21,False,False,Kenya,NaN,NaN,NaN,Dataposit,"['r', 'python', 'matlab', 'java', 'c']","{'programming': ['r', 'python', 'matlab', 'jav...",September
784558,Cloud Engineer,Data Insights Analytics Cloud Support Engineer,"Nairobi, Kenya",via BrighterMonday,Full-time,False,Kenya,2023-11-16 06:31:16,False,False,Kenya,NaN,NaN,NaN,confidential,"['python', 'r', 'ruby', 'ruby', 'go', 'java', ...","{'cloud': ['aws', 'redshift', 'oracle'], 'data...",November
784798,Senior Data Scientist,Senior Analyst,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,2023-10-29 06:22:25,False,False,Kenya,NaN,NaN,NaN,Habitat for Humanity International,"['sas', 'sas', 'r', 'tableau']","{'analyst_tools': ['sas', 'tableau'], 'program...",October
784991,Cloud Engineer,Senior Engineering Technician,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-08-12 06:19:49,True,False,Kenya,NaN,NaN,NaN,Kenya Marine and Fisheries Research Institute ...,['c'],{'programming': ['c']},August
785115,Data Analyst,Data Analyst.,"Nairobi, Kenya",via Trabajo.org,Full-time,False,Kenya,2023-05-31 06:25:53,False,False,Kenya,NaN,NaN,NaN,Supreme,"['sql', 'python', 'r', 'excel', 'tableau', 'po...","{'analyst_tools': ['excel', 'tableau', 'power ...",May

In [7]:
# putting months along the index in correct order and job titles along the columns

df_kenya_pivot = df_kenya.pivot_table(index='job_posted_month', columns='job_title', aggfunc='count')

In [8]:
df_kenya_pivot.reset_index(inplace=True)
df_kenya_pivot['month_no'] = pd.to_datetime(df_kenya_pivot['job_posted_month'], format='%B').dt.month
df_kenya_pivot.sort_values('month_no', inplace=True)
df_kenya_pivot.set_index('job_posted_month', inplace=True)
df_kenya_pivot.drop(columns='month_no', inplace=True)

df_kenya_pivot

                                       company_name  \
job_title        2 Jobs In Kenya Today At Safaricom
job_posted_month
January                                         NaN
February                                        NaN
March                                           NaN
April                                           NaN
May                                             NaN
June                                            NaN
July                                            1.0
August                                          NaN
September                                       NaN
October                                         NaN
November                                        NaN
December                                        NaN

                                                      \
job_title        2 Kenya Airways Jobs In Kenya Today
job_posted_month
January                                          NaN
February                                         NaN
March                                            NaN
April                                            NaN
May                                              NaN
June                                             NaN
July                                             NaN
August                                           1.0
September                                        NaN
October                                          NaN
November                                         NaN
December                                         NaN

                                                      \
job_title        80354357 - Analyst, Finance Systems
job_posted_month
January                                          NaN
February                                         1.0
March                                            NaN
April                                            NaN
May                                              NaN
June                                             NaN
July                                             NaN
August                                           NaN
September                                        NaN
October                                          NaN
November                                         NaN
December                                         NaN

                                                                      \
job_title        80419023 - Scientist, Data A/P Analyst AI Scientist
job_posted_month
January                                 NaN         NaN          NaN
February                                NaN         NaN          NaN
March                                   NaN         NaN          NaN
April                                   NaN         NaN          NaN
May                                     NaN         NaN          NaN
June                                    NaN         NaN          1.0
July                                    NaN         NaN          1.0
August                                  NaN         1.0          NaN
September                               1.0         NaN          NaN
October                                 NaN         NaN          NaN
November                                NaN         NaN          NaN
December                                NaN         NaN          NaN

                                                            \
job_title        AI Software Engineer API Business Analyst
job_posted_month
January                           1.0                  NaN
February                          1.0                  NaN
March                             NaN                  NaN
April                             NaN                  NaN
May                               NaN                  NaN
June                              NaN                  1.0
July                              NaN                  NaN
August                            NaN                  NaN
September                         NaN                  NaN
October                           NaN                  NaN
November                          NaN                  NaN
December                          NaN                  NaN

                                                       \
job_title        ASSOCIATE DATA SCIENTIST [Temporary]
job_posted_month
January                                           NaN
February                                          NaN
March                                             NaN
April                                             NaN
May                                               NaN
June                                              NaN
July                                              NaN
August                                            1.0
September                                         NaN
October                                           NaN
November                                          NaN
December                                          NaN

                                                                          ...  \
job_title        Absa Bank Limited – Business Intelligence Data Engineer  ...
job_posted_month                                                          ...
January                                                         NaN       ...
February                                                        NaN       ...
March                                                           NaN       ...
April                                                           NaN       ...
May                                                             NaN       ...
June                                                            1.0       ...
July                                                            NaN       ...
August                                                          NaN       ...
September                                                       NaN       ...
October                                                         NaN       ...
November                                                        NaN       ...
December                                                        NaN       ...

                          search_location                          \
job_title        associate data scientist data analysis assistant
job_posted_month
January                               NaN                     NaN
February                              NaN                     NaN
March                                 NaN                     NaN
April                                 NaN                     NaN
May                                   NaN                     1.0
June                                  NaN                     NaN
July                                  NaN                     NaN
August                                1.0                     NaN
September                             NaN                     NaN
October                               NaN                     NaN
November                              NaN                     NaN
December                              NaN                     NaN

                                                                       \
job_title        data analyst data analyst/data modeler data engineer
job_posted_month
January                   1.0                       NaN           NaN
February                  NaN                       NaN           NaN
March                     NaN                       NaN           NaN
April                     NaN                       NaN           NaN
May                       NaN                       NaN           NaN
June                      NaN                       NaN           NaN
July                      NaN                       1.0           NaN
August                    NaN                       1.0           NaN
September                 1.0                       NaN           NaN
October                   NaN                       NaN           NaN
November                  NaN                       NaN           NaN
December                  NaN                       NaN           1.0

                                                 \
job_title        data entry it service engineer
job_posted_month
January                 NaN                 NaN
February                NaN                 NaN
March                   1.0                 1.0
April                   NaN                 NaN
May                     NaN                 NaN
June                    NaN                 NaN
July                    NaN                 NaN
August                  NaN                 NaN
September               NaN                 NaN
October                 NaN                 NaN
November                NaN                 NaN
December                NaN                 NaN

                                                                     \
job_title        mPharma – Business Analyst Intern sql data analyst
job_posted_month
January                                        NaN              NaN
February                                       NaN              NaN
March                                          NaN              NaN
April                                          NaN              NaN
May                                            NaN              NaN
June                                           NaN              NaN
July                                           1.0              2.0
August                                         NaN              NaN
September                                      NaN              NaN
October                                        NaN              NaN
November                                       NaN              NaN
December                                       NaN              NaN


job_title        world class data science and machine learning course program
job_posted_month
January                                                         1.0
February                                                        NaN
March                                                           NaN
April                                                           NaN
May                                                             NaN
June                                                            NaN
July                                                            NaN
August                                                          NaN
September                                                       NaN
October                                                         NaN
November                                                        NaN
December                                                        NaN

[12 rows x 16368 columns]

In [9]:
top_3 = df_kenya['job_title_short'].value_counts().head(3)
top_3.index.tolist()

['Data Analyst', 'Software Engineer', 'Data Scientist']

In [10]:
top_3 = top_3.index.tolist()

In [11]:
import matplotlib.pyplot as plt


# aggregate counts across the top-level of the MultiIndex columns so job titles become columns
df_counts = df_kenya_pivot.groupby(level=1, axis=1).sum()

# plot the top 3 job titles
df_counts[top_3].plot(kind='line', marker='o')
plt.title('Monthly job postings for top 3 job titles in Kenya')
plt.ylabel('Count')
plt.xlabel('2023 Months')
plt.show()

TypeError: DataFrame.groupby() got an unexpected keyword argument 'axis'